# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.CharField(max_length=100)),
                ('value_date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('debit', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Person')),
            ],
        ),
    ]
